mybatis:
  mapperLocations: classpath:mybatis/*-mapper.xml
  config: classpath:mybatis/mybatis-conf.xml
  typeAliasesPackage: me.kaohongshu.tuicool
  checkConfigLocation: false


spring:
  datasource:
    url: jdbc:mysql://101.200.34.13:3306/crawl
    username: admin
    password: onetwothree
    driver-class-name: com.mysql.cj.jdbc.Driver
    poolPingEnabled: true
    poolPingQuery: select now() from tuicool limit 1
    poolPingConnectionsNotUsedFor: 3600